# version: '3.8'

services:
  partners: # Definição do serviço remote
    build:
      context: ../partners # Caminho para o diretório do MFE remote
      dockerfile: Dockerfile # Nome do Dockerfile, se for diferente
    ports:
      - '5003:80' # Mapeamento de porta

  auth: # Definição do serviço remote
    build:
      context: ../auth # Caminho para o diretório do MFE remote
      dockerfile: Dockerfile # Nome do Dockerfile, se for diferente
    ports:
      - '5002:80' # Mapeamento de porta

  components: # Definição do serviço remote
    build:
      context: ../components # Caminho para o diretório do MFE remote
      dockerfile: Dockerfile # Nome do Dockerfile, se for diferente
    ports:
      - '5001:80' # Mapeamento de porta

  app: # Definição do serviço host
    build: .
    ports:
      - '5000:80' # Mapeamento de porta
    depends_on:
      - components # Garantindo que o serviço remote esteja disponível antes de iniciar o host
      - auth # Garantindo que o serviço remote esteja disponível antes de iniciar o host
      - partners # Garantindo que o serviço remote esteja disponível antes de iniciar o host
